{
  "name": "await-catch",
  "version": "1.0.0",
  "description": "Async await wrapper for easy error handling",
  "main": "./src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "async-await",
    "async",
    "catch",
    "try-catch",
    "try",
    "catch",
    "es6"
  ],
  "bugs": {
    "url": "https://github.com/bufface/await-catch/issues",
    "email": "bufface@gmail.com"
  },
  "homepage": "https://github.com/bufface/await-catch",
  "repository": {
    "type": "git",
    "url": "https://github.com/bufface/await-catch"
  },
  "author": "Cristian Buffa <bufface@gmail.com> (https://github.com/bufface)",
  "license": "MIT"
}
